### ISSUE TITLE
The application is down

### ISSUE THREAD

**Issue by marzn** [opendatacity/vds-suisse#4]
https://apps.opendatacity.de/vds/index_en.html

delivers a `404 Not Found`

**Comment by mvtango** [comment]
You're right - added a redirect to the archive version of the site. It does not have a working map, but one gets the idea.

http://opendatacity.github.io/vds-suisse/
![image](https://user-images.githubusercontent.com/1538368/37762787-99c117f4-2dbd-11e8-830b-16371818d15d.png)

**Comment by MichaelKreil** [comment]
Euch ist schon klar, dass die Grafik in zahlreichen Medien eingebunden ist, und überall nicht mehr funktioniert?
Z.B.:
https://www.nzz.ch/digital/vorratsdaten-veroeffentlicht-nationalrat-balthasar-glaettli-1.18291061
https://www.watson.ch/Schweiz/Digital/204848573---Es-ist-nur-eine-Frage-der-Zeit--bis-der-Bund-auch-Telefongespraeche-und-SMS-speichern-will--
https://www.balthasar-glaettli.ch/vorratsdaten/
https://steigerlegal.ch/2014/04/27/visualisierung-vorratsdatenspeicherung/

**Comment by MichaelKreil** [comment]
So you don't give a fuck?

**Comment by netAction** [comment]
Can confirm. The map is broken.

**Comment by yetzt** [comment]
the broken map could be [easily fixed](https://github.com/opendatacity/vds-suisse/blob/master/docs/script/modules.js#L308). rechnung kommt dann.

**Comment by martinvirtel** [comment]
@yetzt thanks pls send a pull request
